name: Run Tests On JS Client Library

on:
  push:
    paths:
      - "library/client/**"
      - ".github/workflows/run-tests-on-client-library.yaml"

jobs:
  deploy:
    name: Run Tests On JS Client Library
    runs-on: ubuntu-latest
    env:
      RUN_TESTS: ${{ secrets.RUN_TESTS }}

    steps:
      - name: Checkout Files
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        if: ${{ env.RUN_TESTS == 'true' }}
        with:
          node-version: 14

      - name: Run Tests
        if: ${{ env.RUN_TESTS == 'true' }}
        run: |
          cd ./library/client
          npm install
          npm run test
